name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    
    # Set up Python version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies including transformers, torch, and pylint
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint transformers torch

    # Run pylint to analyze the Python code
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
