name: Pylint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest version of the repository
    - name: Check out the repository
      uses: actions/checkout@v4

    # Step 2: Set up Python 3.12.3
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.3

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Install Pylint and additional dependencies needed for the project
    - name: Install Pylint and additional dependencies
      run: |
        pip install pylint
        pip install flask langid

    # Step 5: Run Pylint against Python files in the repository
    - name: Run Pylint
      run: pylint $(git ls-files '*.py')

    # Step 6: Generate Pylint report
    - name: Generate Pylint report
      run: pylint $(git ls-files '*.py') --output=pylint-report.txt
      continue-on-error: true

    # Step 7: Upload Pylint report as an artifact
    - name: Archive pylint report
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: pylint-report.txt
